export type {
  Offer,
  OfferBlock,
  OfferBlockItem,
  OfferAttachment,
  OfferAdjustment,
  AdjustmentComment,
  OfferVersion,
  VersionDiff,
  BlockDiff,
  ItemDiff,
  MenuItem,
  Menu,
  Equipment,
  ServiceItem,
  Discount,
  OfferItemType,
  OfferStatus,
  DiscountType,
  AttachmentType,
  AdjustmentType,
  AdjustmentStatus,
} from './domain.types'
